spring:
  flyway:
    enabled: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost/fksbank?useSSL=false&characterEncoding=UTF-8&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 12345
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 12345
    timeout: 60000